Feature/qualification join contact
Bay-Area-Hackers/community-website pull request #3
Opened 2021-12-29 01:34 UTC by Tatsuya3327

スマホ・タブレット・デスクトップの3つのレスポンシブデザインを反映させました。
https://tailwindcss.com/docs/responsive-design
Tailwind CSS の`sm (min-width: 640px)`と`lg (min-width: 1024px)`を境界にしています。

2021-12-29 02:32 UTC, Sota1221 requested changes
[SHOULD]
実機で確認しました。
スマホ、タブレットの画面は大丈夫だと思います！
PC画面時は、contactの文章が2行にわたるようにしたいので、もう少し左右の余白が欲しいです！
こちらの見本が参考になるかと思います
https://xd.adobe.com/view/30ee993d-970b-441d-9ab2-0db8b6a3fc81-65bd

見本
<img width="1365" alt="Screen Shot 2021-12-28 at 18 23 14" src="https://user-images.githubusercontent.com/25310370/147621826-3ab70014-1b75-415e-87db-7b926310a801.png">
/

今回のコード
<img width="1788" alt="Screen Shot 2021-12-28 at 18 23 30" src="https://user-images.githubusercontent.com/25310370/147621847-72172aa7-9be7-405e-89b3-9b8b502dac14.png">

2021-12-29 07:38 UTC, Tatsuya3327 commented
デスクトップ版のみ%からピクセル表記で固定して常に文章が2行以上になるように変更しました。

2021-12-29 16:05 UTC, Sota1221 approved these changes
スマホ、タブレット、PCが画面で確認しました！
LGTMです😎

2021-12-31 04:44 UTC, YukiOkamoto0206 commented on index.html
> +      </div>
[SHOULD]Sotaさんのfooterブランチとコンフリするので、削除してください！

2021-12-31 04:44 UTC, YukiOkamoto0206 commented on index.html
>      </header>
[SHOULD]これも同様に必要ですかね??

2021-12-31 05:57 UTC, mie-h approved these changes
LGTM! merge conflictは解消されましたか？

2021-12-31 07:52 UTC, merged